'use strict';
/**
 * Link response headers (RFC 8288) plus Markdown content negotiation.
 *
 * Both need the server, not just static files, so this fixer writes whatever the
 * detected host actually reads:
 *   cloudflare-pages -> _headers  + functions/_middleware.js (Accept: text/markdown)
 *   netlify          -> _headers  (+ note about edge functions for negotiation)
 *   vercel           -> vercel.json headers
 *   github-pages     -> no header support; we say so plainly instead of writing a file that does nothing
 *   unknown          -> _headers, which Pages and Netlify both understand
 */
const { json } = require('../util');

/** Relations worth advertising, in the order agents look for them. */
function relations(ctx) {
  const rels = [
    { path: '/.well-known/api-catalog', rel: 'api-catalog' },
    { path: '/llms.txt', rel: 'service-doc' },
  ];
  if (ctx.inputs.openapiUrl) rels.push({ path: ctx.inputs.openapiUrl, rel: 'service-desc' });
  else rels.push({ path: '/.well-known/mcp/server-card.json', rel: 'service-desc' });
  if (ctx.inputs.apiDocsUrl) rels.push({ path: ctx.inputs.apiDocsUrl, rel: 'help' });
  return rels;
}

function headerValue(ctx) {
  return relations(ctx).map(({ path, rel }) => `<${path}>; rel="${rel}"`).join(', ');
}

const MIDDLEWARE = `/**
 * Serves Markdown to agents that ask for it, and advertises agent-facing
 * resources via Link headers (RFC 8288).
 *
 * An agent sending \`Accept: text/markdown\` for /about gets the contents of
 * /about.md with a text/markdown content type. Browsers are unaffected.
 *
 * Generated by agent-ready-action. Safe to edit.
 */
const LINK_HEADER = __LINK_HEADER__;

export async function onRequest(context) {
  const { request, next } = context;
  const url = new URL(request.url);
  const accept = request.headers.get('accept') || '';
  const wantsMarkdown = /text\\/markdown/i.test(accept);

  if (wantsMarkdown && !url.pathname.endsWith('.md')) {
    const base = url.pathname === '/' ? '/index' : url.pathname.replace(/\\/$/, '');
    const mdUrl = new URL(base + '.md', url.origin);
    const md = await context.env.ASSETS
      ? await fetch(mdUrl, request)
      : await fetch(mdUrl.toString(), { headers: request.headers });
    if (md && md.ok) {
      const headers = new Headers(md.headers);
      headers.set('content-type', 'text/markdown; charset=utf-8');
      headers.set('vary', 'Accept');
      headers.set('link', LINK_HEADER);
      return new Response(md.body, { status: 200, headers });
    }
  }

  const response = await next();
  const headers = new Headers(response.headers);
  headers.append('link', LINK_HEADER);
  const vary = headers.get('vary');
  headers.set('vary', vary ? \`\${vary}, Accept\` : 'Accept');
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
`;

function apply(ctx) {
  const value = headerValue(ctx);
  const files = [];
  const notes = [];
  const host = ctx.site.host;

  if (host === 'vercel') {
    // vercel.json lives at the repo root, not the site dir.
    const existing = ctx.readRoot('vercel.json');
    let cfg = {};
    try { cfg = existing ? JSON.parse(existing) : {}; } catch {
      notes.push('Could not parse your existing `vercel.json`; skipped header config. Add the Link header manually.');
      return files.length ? { files, notes } : null;
    }
    cfg.headers = Array.isArray(cfg.headers) ? cfg.headers : [];
    const already = cfg.headers.some((h) => (h.headers || []).some((x) => String(x.key).toLowerCase() === 'link'));
    if (already) return null;
    cfg.headers.push({
      source: '/(.*)',
      headers: [
        { key: 'Link', value },
        { key: 'Vary', value: 'Accept' },
      ],
    });
    files.push({ path: 'vercel.json', contents: json(cfg), atRoot: true });
    notes.push('Added a `Link` header to `vercel.json` for every route.');
    notes.push('Markdown negotiation on Vercel needs middleware — see `docs/agent-ready/markdown-negotiation.md` in this PR.');
    files.push(negotiationDoc(ctx, value));
    return { files, notes };
  }

  if (host === 'github-pages') {
    notes.push('**GitHub Pages cannot set custom response headers**, so `linkHeaders` and `markdownNegotiation` cannot pass there. Everything else in this PR still applies. To pass those two checks, put the site behind Cloudflare Pages, Netlify, or a Worker.');
    files.push(negotiationDoc(ctx, value));
    return { files, notes };
  }

  // Cloudflare Pages, Netlify, and anything unknown all understand `_headers`.
  const existingHeaders = ctx.read('_headers');
  if (!existingHeaders || !/^\s*link:/im.test(existingHeaders)) {
    const block = [
      '# Agent discovery headers (RFC 8288). Generated by agent-ready-action.',
      '/*',
      `  Link: ${value}`,
      '  Vary: Accept',
      '',
    ].join('\n');
    files.push({
      path: '_headers',
      contents: existingHeaders ? existingHeaders.replace(/\s*$/, '\n') + '\n' + block : block,
    });
    notes.push(existingHeaders
      ? 'Appended a `Link` header rule to your existing `_headers`.'
      : 'Created `_headers` with a site-wide `Link` header.');
  }

  // Cloudflare Pages is the one host where we can wire negotiation up directly.
  // Everywhere else gets the snippet to paste. A middleware that already exists
  // is left alone, and does not fall through to the doc — that would make a
  // rerun write a file it did not need to.
  if (host === 'cloudflare-pages') {
    const existingMiddleware = ctx.readRoot('functions/_middleware.js') || ctx.readRoot('functions/_middleware.ts');
    if (!existingMiddleware) {
      files.push({
        path: 'functions/_middleware.js',
        atRoot: true,
        contents: MIDDLEWARE.replace('__LINK_HEADER__', JSON.stringify(value)),
      });
      notes.push('Added a Cloudflare Pages middleware that answers `Accept: text/markdown` with your `.md` twins — that is what makes `markdownNegotiation` pass.');
    } else {
      notes.push('You already have `functions/_middleware.js`; it was left untouched. Make sure it handles `Accept: text/markdown` — see `docs/agent-ready/markdown-negotiation.md` if you need the snippet.');
    }
  } else {
    files.push(negotiationDoc(ctx, value));
    notes.push('Markdown content negotiation needs a server hook on this host — the PR includes a copy-paste snippet at `docs/agent-ready/markdown-negotiation.md`.');
  }

  if (!files.length) return null;
  return { files, notes };
}

function negotiationDoc(ctx, linkValue) {
  const contents = `# Markdown content negotiation

The Agent Readiness \`markdownNegotiation\` check passes when a request carrying
\`Accept: text/markdown\` gets Markdown back instead of HTML. Static files alone
cannot do that — it needs a hook at the edge. Below is the snippet for common
hosts. Your \`.md\` twins are already committed alongside your pages.

Detected host: **${ctx.site.host}** · framework: **${ctx.site.framework}**

## Link header value

\`\`\`
Link: ${linkValue}
Vary: Accept
\`\`\`

## Cloudflare Pages / Workers

\`\`\`js
// functions/_middleware.js
export async function onRequest({ request, next }) {
  const url = new URL(request.url);
  if (/text\\/markdown/i.test(request.headers.get('accept') || '') && !url.pathname.endsWith('.md')) {
    const base = url.pathname === '/' ? '/index' : url.pathname.replace(/\\/$/, '');
    const md = await fetch(new URL(base + '.md', url.origin), request);
    if (md.ok) {
      const headers = new Headers(md.headers);
      headers.set('content-type', 'text/markdown; charset=utf-8');
      headers.set('vary', 'Accept');
      return new Response(md.body, { headers });
    }
  }
  return next();
}
\`\`\`

## Vercel

\`\`\`js
// middleware.js
export const config = { matcher: '/((?!_next|.*\\\\.).*)' };

export function middleware(request) {
  const accept = request.headers.get('accept') || '';
  if (!/text\\/markdown/i.test(accept)) return;
  const url = new URL(request.url);
  const base = url.pathname === '/' ? '/index' : url.pathname.replace(/\\/$/, '');
  return Response.redirect(new URL(base + '.md', url.origin), 303);
}
\`\`\`

## Netlify

Use an [edge function](https://docs.netlify.com/edge-functions/overview/) with the
same logic as the Cloudflare snippet, declared in \`netlify.toml\`:

\`\`\`toml
[[edge_functions]]
  function = "markdown"
  path = "/*"
\`\`\`

## Nginx

\`\`\`nginx
location / {
  if ($http_accept ~* "text/markdown") {
    rewrite ^(.*)$ $1.md last;
  }
  try_files $uri $uri/ /index.html;
}
\`\`\`
`;
  return { path: 'docs/agent-ready/markdown-negotiation.md', contents, atRoot: true };
}

module.exports = {
  id: 'linkHeaders',
  checks: ['linkHeaders'],
  title: 'Link headers and Markdown negotiation',
  category: 'discoverability',
  apply,
  headerValue,
};
